language: generic

services:
  - docker

env:
  global:
    # - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  # Unencrypt service-account.json.enc for use with gcloud auth
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d

  # Install Google Cloud SDK
  - curl https://sdk.cloud.google.com > install.sh
  - bash install.sh --disable-prompts
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  # gcloud auth
  - gcloud auth activate-service-account --key-file service-account.json
  # gcloud config project and compute zone
  - gcloud config set project linen-office-303223
  - gcloud config set compute/zone us-west1-a
  # gcloud cluster setup
  - gcloud container clusters get-credentials multi-cluster

  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Build image for testing
  - docker build -t chejll/multi-client-test --file ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chejll/multi-client-test yarn test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
