version: '3'

services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    networks:
      - complex
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    # ports:
    #   - "3000:3000"
    volumes:
      - /data/app/node_modules
      - ./client:/data/app
    networks:
      - complex
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file:
      - env/redis.env
      - env/postgres.env
    # ports:
    #   - "5000:5000"
    volumes:
      - /data/app/node_modules
      - ./server:/data/app
    networks:
      - complex
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    env_file:
      - env/redis.env
    volumes:
      - /data/app/node_modules
      - ./worker:/data/app
    networks:
      - complex
  postgres:
    image: postgres:13
    env_file:
      - env/postgres.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - complex
  redis:
    image: redis:6
    volumes:
      - ./data/redis:/data
    networks:
      - complex

networks:
  complex:
    driver: bridge
