apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tenthirteen-dev
spec:
  secretName: tenthirteen-dev-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: tenthirteen.dev
  dnsNames:
    - tenthirteen.dev
    - www.tenthirteen.dev
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - tenthirteen.dev
          - www.tenthirteen.dev
